#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
		KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_NO,
		KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_NO,
		KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B,
		KC_LOPT, FN_MO13, KC_ENT,
		KC_BSPC, KC_P, KC_O, KC_I, KC_U, KC_Y, KC_NO,
		KC_ESC, KC_SCLN, KC_L, KC_K, KC_J, KC_H, KC_NO,
		KC_QUOT, KC_SLSH, KC_DOT, KC_COMM, KC_M, KC_N,
		KC_LGUI, FN_MO23, KC_SPC
	),
	[1] = LAYOUT(
		KC_TAB, KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LCTL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_LOPT, KC_TRNS, KC_ENT,
		KC_BSPC, KC_0, KC_9, KC_8, KC_7, KC_6, KC_NO,
		KC_NO, KC_NO, KC_RGHT, KC_UP, KC_DOWN, KC_LEFT, KC_NO,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_RGUI, KC_TRNS, KC_SPC
	),
	[2] = LAYOUT(
		KC_TAB, LSFT(KC_1), LSFT(KC_2), LSFT(KC_3), LSFT(KC_4), LSFT(KC_5), KC_NO,
		KC_LSFT, KC_NO, LSFT(KC_6), KC_QUOT, LSFT(KC_GRV), KC_CAPS, KC_NO,
		KC_LCTL, KC_NO, KC_NO, RALT(KC_COMM), KC_NO, KC_NO,
		KC_LOPT, KC_TRNS, KC_ENT,
		KC_BSPC, LSFT(KC_0), LSFT(KC_9), LSFT(KC_8), LSFT(KC_7), LSFT(KC_6), KC_NO,
		KC_GRV, KC_BSLS, KC_RBRC, KC_LBRC, KC_EQL, KC_MINS, KC_NO,
		LSFT(KC_GRV), LSFT(KC_BSLS), LSFT(KC_RBRC), LSFT(KC_LBRC), LSFT(KC_EQL), LSFT(KC_MINS),
		KC_RGUI, KC_TRNS, KC_SPC
	),
	[3] = LAYOUT(
		KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_NO,
		KC_LSFT, RGB_VAI, RGB_HUI, KC_VOLU, KC_PSCR, KC_NO, KC_NO,
		KC_LCTL, RGB_VAD, RGB_HUD, KC_VOLD, KC_NO, KC_NO,
		KC_LOPT, KC_TRNS, KC_ENT,
		KC_DEL, KC_F10, KC_F9, KC_F8, KC_F7, KC_F6, KC_NO,
		KC_BTN2, KC_BTN1, KC_MS_R, KC_MS_U, KC_MS_D, KC_MS_L, KC_NO,
		KC_F12, KC_F11, KC_NO, KC_WH_U, KC_WH_D, KC_NO,
		KC_RGUI, KC_TRNS, KC_SPC
	),
	[4] = LAYOUT(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS
	),
	[5] = LAYOUT(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS
	)
};

